INSERT INTO dataco_cleaned
SELECT 
    "Type",
    "Days for shipping (real)"::INTEGER,
    "Days for shipment (scheduled)"::INTEGER,
    "Benefit per order"::NUMERIC,
    "Sales per customer"::NUMERIC,
    "Delivery Status",
    "Late_delivery_risk"::INTEGER,
    "Category Id"::INTEGER,
    "Category Name",
    "Customer City",
    "Customer Country",
    "Customer Email",
    "Customer Fname",
    "Customer Id"::INTEGER,
    "Customer Lname",
    "Customer Segment",
    "Customer State",
    "Customer Street",
    "Customer Zipcode",
    "Department Id"::INTEGER,
    "Department Name",
    "Latitude"::DOUBLE PRECISION,
    "Longitude"::DOUBLE PRECISION,
    "Market",
    "Order City",
    "Order Country",
    "Order Customer Id"::INTEGER,
    TO_TIMESTAMP("order date (DateOrders)", 'MM/DD/YYYY HH24:MI'), -- Sesuaikan format tanggal di CSV
    "Order Id"::INTEGER,
    "Order Item Cardprod Id"::INTEGER,
    "Order Item Discount"::NUMERIC,
    "Order Item Discount Rate"::NUMERIC,
    "Order Item Id"::INTEGER,
    "Order Item Product Price"::NUMERIC,
    "Order Item Profit Ratio"::NUMERIC,
    "Order Item Quantity"::INTEGER,
    "Sales"::NUMERIC,
    "Order Item Total"::NUMERIC,
    "Order Profit Per Order"::NUMERIC,
    "Order Region",
    "Order State",
    "Order Status",
    "Order Zipcode",
    "Product Card Id"::INTEGER,
    "Product Category Id"::INTEGER,
    "Product Description",
    "Product Image",
    "Product Name",
    "Product Price"::NUMERIC,
    "Product Status"::INTEGER,
    TO_TIMESTAMP("shipping date (DateOrders)", 'MM/DD/YYYY HH24:MI'),
    "Shipping Mode"
FROM dataco_raw;